-- #######################################################################################
-- AUTOGENERATED HYPRLAND CONFIG.
-- PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hyprland.conf AND EDIT IT,
-- OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
-- #######################################################################################

-- This is an example Hyprland config file.
-- Refer to the wiki for more information.
-- https://wiki.hyprland.org/Configuring/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can split this configuration into multiple files
-- Create your files separately and then link them to this file like this:
-- source = ~/.config/hypr/myColors.conf

--##################
--## MY PROGRAMS ###
--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/

-- Set programs that you use
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

terminal = "alacritty"
fileManager = "thunar"
menu = "rofi -show drun -case-smart -matching fuzzy -sort -sorting-method fzf"

--################
--## AUTOSTART ###
--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:

--exec-once  = [workspace 7 silent] proton-mail
--windowrule = match:class (^proton-mail$), workspace 7 silent

hl.window_rule({
    match = {
        class = "(^discord$)",
    },
    workspace = "9 silent",
})

hl.window_rule({
    match = {
        class = "(^signal-desktop$)",
    },
    workspace = "9 silent",
})

hl.window_rule({
    match = {
        class = "(^waydroid$)",
    },
    workspace = "6 silent",
})

hl.window_rule({
    match = {
        class = "(^steam$)",
    },
    workspace = "8 silent",
})

--############################
--## ENVIRONMENT VARIABLES ###
--############################

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

hl.env("LIBVA_DRIVER_NAME", "radeonsi")
hl.env("VDPAU_DRIVER", "radeonsi")

-- Source: ./general.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("general")
-- Source: ./io.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("io")
-- Source: ./binds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("binds")

--#############################
--## WINDOWS AND WORKSPACES ###
--#############################

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
-- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

hl.window_rule({
    match = {
        class = "^(dialog)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(splash)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Volume Control)$",
    },
    float = true,
    size = "30% 30%",
    move = "69% 5%",
})

hl.window_rule({
    match = {
        class = "^(blueman-manager)$",
    },
    float = true,
    size = "30% 30%",
    move = "69% 5%",
})

hl.window_rule({
    match = {
        class = "^(nm-connection-editor)$",
    },
    float = true,
    size = "30% 30%",
    move = "69% 5%",
})

hl.window_rule({
    match = {
        class = "^(nm-connection-editor)$ title:^(Editing (.*))$",
    },
    center = true,
})

hl.window_rule({
    match = {
        title = "^(rofi (.*))$",
    },
    stay_focused = true,
})

-- Ignore maximize requests from apps. You'll probably like this.
hl.window_rule({
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

-- Fix some dragging issues with XWayland
-- windowrule = nofocus, class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

hl.window_rule({
    match = {
        class = "^steam_app\\d+$",
    },
    fullscreen = true,
})

hl.window_rule({
    match = {
        class = "^steam_app_\\d+$",
    },
    monitor = "1",
    workspace = "10",
})

hl.workspace_rule({
   workspace = "1",
    default_name = "terminal",
    monitor = "DP-1",
    default = true,
})

hl.workspace_rule({
    workspace = "2",
    default_name = "browser",
    monitor = "DVI-D-1",
    default = true,
})

hl.workspace_rule({
    workspace = "7",
    default_name = "mail",
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = "8",
    default_name = "steam",
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = "9",
    default_name = "social",
    monitor = "HDMI-A-1",
    default = true,
})

hl.workspace_rule({
    workspace = "10",
    default_name = "games",
    monitor = "DP-1",
    no_border = true,
    no_rounding = true,
})

-- Unblur some applications
hl.window_rule({
    match = {
        class = "^(firefox)$",
    },
    opacity = "1.0 override 1.0 override",
})

hl.window_rule({
    match = {
        class = "^((.*)chrome)$",
    },
    opacity = "1.0 override 1.0 override",
})

hl.on("hyprland.start", function()
    hl.exec_cmd("hyprlock --immediate")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("hyprctl dispatch exec waybar")
    hl.exec_cmd("hyprpaper --config ~/.config/hypr/hyprpaper.conf")
    hl.exec_cmd("wl-paste --type text  --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("wlsunset -l 45.46 -L -73.74 -t 5000 -T 8000")
    hl.exec_cmd("~/.config/hypr/volume_control.sh")
    hl.exec_cmd("xrandr --output DP-1 --primary")
    hl.exec_cmd("fcitx5")
    hl.exec_cmd("/usr/lib/kdeconnectd")
    hl.exec_cmd("kdeconnect-indicator")
    hl.exec_cmd("firefox", { workspace = "2 silent" })
    hl.exec_cmd("discord", { workspace = "9 silent" })
    hl.exec_cmd("signal-desktop", { workspace = "9 silent" })
    hl.exec_cmd("element-desktop", { workspace = "9 silent" })
    hl.exec_cmd("hyprctl dispatch exec [workspace 8 silent] `steam -cef-disable-gpu`")
end)

