--###############
--## MONITORS ###
--###############

-- See https://wiki.hyprland.org/Configuring/Monitors/
--monitor = DP-1    , 2560x1440@144, 0x0      , 1
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "DP-1",
    mode = "2560x1440@144",
    position = "0x0",
    scale = "1",
})

hl.monitor({
    output = "DP-2",
    mode = "1920x1080@60",
    position = "2560x300",
    scale = "1",
})

hl.monitor({
    output = "HDMI-A-1",
    mode = "1680x1050",
    position = "2560x-750",
    scale = "1",
})

--monitor = DVI-D-1 , 1680x1050    , 2560x450 , 1
hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "1",
})

--monitor = DVI-D-1 , disable
--monitor = HDMI-A-1, disable

--############
--## INPUT ###
--############

-- https://wiki.hyprland.org/Configuring/Variables/#input
hl.config({
    input = {
        kb_layout = "ca",
        kb_variant = "multix",
        --kb_variant = coolmak
        kb_model = "",
        kb_options = "",
        kb_rules = "",
        follow_mouse = 2,
        sensitivity = 0,
        accel_profile = "flat",
        --force_no_accel = true
        repeat_rate = 30,
        repeat_delay = 300, --150
        touchpad = {
            natural_scroll = false,
        },
        numlock_by_default = true,
    },
})

