--###############
--## MONITORS ###
--###############

-- See https://wiki.hyprland.org/Configuring/Monitors/
--monitor = DP-1    , 2560x1440@144, 0x0      , 1
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "DP-1",
    mode = "2560x1440@144",
    position = "0x0",
    scale = "1",
})

hl.monitor({
    output = "DP-2",
    mode = "1920x1080@60",
    position = "2560x300",
    scale = "1",
})

hl.monitor({
    output = "HDMI-A-1",
    mode = "1680x1050",
    position = "2560x-750",
    scale = "1",
})

--monitor = DVI-D-1 , 1680x1050    , 2560x450 , 1
hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "1",
})

--monitor = DVI-D-1 , disable
--monitor = HDMI-A-1, disable

